on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm --recursive run build
      - run: pnpm  prettier . -c
      - run: pnpm eslint .
      - run: pnpm run --recursive test
